let arr = [

    {
        name: "Bricks",
        icon: "https://static.wikia.nocookie.net/against-the-storm/images/d/d5/Icon_Resource_Bricks.png/revision/latest/scale-to-width-down/25?cb=20221025150532",
        rarity: "",
        tags: [],
        craftable: {
            // указать здания, бонусы расс, ресы для здания, ресы для ресов зданий, здания для ресов для зданий, бонусы для расс  для ресов для зданий
            T1: [
                { res: "asdasd", quantity: 2 }
            ],
            T2: [
                { res: "asdasd", quantity: 2 }
            ],

            T3: [
                { res: "asdasd", quantity: 2 }
            ],

        }
    },
    {
        name: "",
        icon: "",
        rarity: "",
        tags: [],
    },
]
    < ul ><li><span class="new" title="Building Materials (page does not exist)" data-uncrawlable-url="L3dpa2kvQnVpbGRpbmdfTWF0ZXJpYWxzP2FjdGlvbj1lZGl0JnJlZGxpbms9MQ==">Building Materials</span>
    <ul><li><a href="/wiki/Bricks" title="Bricks"><img alt="Icon Resource Bricks.png" 
    src="https://static.wikia.nocookie.net/against-the-storm/images/d/d5/Icon_Resource_Bricks.png/revision/latest/scale-to-width-down/25?cb=20221025150532" decoding="async" loading="lazy" data-image-name="Icon Resource Bricks.png"
     data-image-key="Icon_Resource_Bricks.png" width="25" height="25"></a> <a href="/wiki/Bricks" title="Bricks">Bricks</a></li>
        <li><a href="/wiki/Fabric" title="Fabric"><img alt="Icon Resource Fabric.png" src="https://static.wikia.nocookie.net/against-the-storm/images/d/d6/Icon_Resource_Fabric.png/revision/latest/scale-to-width-down/25?cb=20221013131626" decoding="async" loading="lazy" data-image-name="Icon Resource Fabric.png" data-image-key="Icon_Resource_Fabric.png" width="25" height="25"></a> <a href="/wiki/Fabric" title="Fabric">Fabric</a></li>
        <li><a href="/wiki/Parts" title="Parts"><img alt="Icon Resource Parts.png" src="https://static.wikia.nocookie.net/against-the-storm/images/8/85/Icon_Resource_Parts.png/revision/latest/scale-to-width-down/25?cb=20221025150911" decoding="async" loading="lazy" data-image-name="Icon Resource Parts.png" data-image-key="Icon_Resource_Parts.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/8/85/Icon_Resource_Parts.png/revision/latest/scale-to-width-down/25?cb=20221025150911" class=" ls-is-cached lazyloaded" width="25" height="25"></a> <a href="/wiki/Parts" title="Parts">Parts</a></li>
        <li><a href="/wiki/Planks" title="Planks"><img alt="Icon Resource Planks.png" src="https://static.wikia.nocookie.net/against-the-storm/images/0/01/Icon_Resource_Planks.png/revision/latest/scale-to-width-down/25?cb=20221013133216" decoding="async" loading="lazy" data-image-name="Icon Resource Planks.png" data-image-key="Icon_Resource_Planks.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/0/01/Icon_Resource_Planks.png/revision/latest/scale-to-width-down/25?cb=20221013133216" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Planks" title="Planks">Planks</a></li>
        <li><a href="/wiki/Wildfire_Essence" title="Wildfire Essence"><img alt="MiningIcons 73 b.png" src="https://static.wikia.nocookie.net/against-the-storm/images/9/94/MiningIcons_73_b.png/revision/latest/scale-to-width-down/25?cb=20221013154418" decoding="async" loading="lazy" data-image-name="MiningIcons 73 b.png" data-image-key="MiningIcons_73_b.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/9/94/MiningIcons_73_b.png/revision/latest/scale-to-width-down/25?cb=20221013154418" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Wildfire_Essence" title="Wildfire Essence">Wildfire Essence</a></li></ul></li>
    <li><span class="new" title="Consumable Items (page does not exist)" data-uncrawlable-url="L3dpa2kvQ29uc3VtYWJsZV9JdGVtcz9hY3Rpb249ZWRpdCZyZWRsaW5rPTE=">Consumable Items</span>
        <ul><li><a href="/wiki/Ale" title="Ale"><img alt="Icon Resource Ale.png" src="https://static.wikia.nocookie.net/against-the-storm/images/a/a9/Icon_Resource_Ale.png/revision/latest/scale-to-width-down/25?cb=20221013140800" decoding="async" loading="lazy" data-image-name="Icon Resource Ale.png" data-image-key="Icon_Resource_Ale.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/a/a9/Icon_Resource_Ale.png/revision/latest/scale-to-width-down/25?cb=20221013140800" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Ale" title="Ale">Ale</a></li>
            <li><a href="/wiki/Coats" title="Coats"><img alt="Icon Resource Coats.png" src="https://static.wikia.nocookie.net/against-the-storm/images/3/3a/Icon_Resource_Coats.png/revision/latest/scale-to-width-down/25?cb=20221013141425" decoding="async" loading="lazy" data-image-name="Icon Resource Coats.png" data-image-key="Icon_Resource_Coats.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/3/3a/Icon_Resource_Coats.png/revision/latest/scale-to-width-down/25?cb=20221013141425" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Coats" title="Coats">Coats</a></li>
            <li><a href="/wiki/Cosmetics" title="Cosmetics"><img alt="Icon Resource Cosmetics.png" src="https://static.wikia.nocookie.net/against-the-storm/images/a/a1/Icon_Resource_Cosmetics.png/revision/latest/scale-to-width-down/25?cb=20221013141847" decoding="async" loading="lazy" data-image-name="Icon Resource Cosmetics.png" data-image-key="Icon_Resource_Cosmetics.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/a/a1/Icon_Resource_Cosmetics.png/revision/latest/scale-to-width-down/25?cb=20221013141847" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Cosmetics" title="Cosmetics">Cosmetics</a></li>
            <li><a href="/wiki/Incense" title="Incense"><img alt="Icon Resource Incense.png" src="https://static.wikia.nocookie.net/against-the-storm/images/e/ea/Icon_Resource_Incense.png/revision/latest/scale-to-width-down/25?cb=20221013142930" decoding="async" loading="lazy" data-image-name="Icon Resource Incense.png" data-image-key="Icon_Resource_Incense.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/e/ea/Icon_Resource_Incense.png/revision/latest/scale-to-width-down/25?cb=20221013142930" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Incense" title="Incense">Incense</a></li>
            <li><a href="/wiki/Scrolls" title="Scrolls"><img alt="Icon Resource Scrolls.png" src="https://static.wikia.nocookie.net/against-the-storm/images/f/f7/Icon_Resource_Scrolls.png/revision/latest/scale-to-width-down/25?cb=20221013150348" decoding="async" loading="lazy" data-image-name="Icon Resource Scrolls.png" data-image-key="Icon_Resource_Scrolls.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/f/f7/Icon_Resource_Scrolls.png/revision/latest/scale-to-width-down/25?cb=20221013150348" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Scrolls" title="Scrolls">Scrolls</a></li>
            <li><a href="/wiki/Training_Gear" title="Training Gear"><img alt="Icon Resource TrainingGear.png" src="https://static.wikia.nocookie.net/against-the-storm/images/3/38/Icon_Resource_TrainingGear.png/revision/latest/scale-to-width-down/25?cb=20221013150551" decoding="async" loading="lazy" data-image-name="Icon Resource TrainingGear.png" data-image-key="Icon_Resource_TrainingGear.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/3/38/Icon_Resource_TrainingGear.png/revision/latest/scale-to-width-down/25?cb=20221013150551" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Training_Gear" title="Training Gear">Training Gear</a></li>
            <li><a href="/wiki/Wine" title="Wine"><img alt="Icon Resource Wine.png" src="https://static.wikia.nocookie.net/against-the-storm/images/a/a1/Icon_Resource_Wine.png/revision/latest/scale-to-width-down/25?cb=20221013150803" decoding="async" loading="lazy" data-image-name="Icon Resource Wine.png" data-image-key="Icon_Resource_Wine.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/a/a1/Icon_Resource_Wine.png/revision/latest/scale-to-width-down/25?cb=20221013150803" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Wine" title="Wine">Wine</a></li></ul></li>
    <li><span class="new" title="Crafting Resources (page does not exist)" data-uncrawlable-url="L3dpa2kvQ3JhZnRpbmdfUmVzb3VyY2VzP2FjdGlvbj1lZGl0JnJlZGxpbms9MQ==">Crafting Resources</span>
        <ul><li><a href="/wiki/Barrels" title="Barrels"><img alt="Icon Resource Barrels.png" src="https://static.wikia.nocookie.net/against-the-storm/images/8/88/Icon_Resource_Barrels.png/revision/latest/scale-to-width-down/25?cb=20221013153209" decoding="async" loading="lazy" data-image-name="Icon Resource Barrels.png" data-image-key="Icon_Resource_Barrels.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/8/88/Icon_Resource_Barrels.png/revision/latest/scale-to-width-down/25?cb=20221013153209" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Barrels" title="Barrels">Barrels</a></li>
            <li><a href="/wiki/Clay" title="Clay"><img alt="Icon Resource Clay.png" src="https://static.wikia.nocookie.net/against-the-storm/images/c/ca/Icon_Resource_Clay.png/revision/latest/scale-to-width-down/25?cb=20221013133435" decoding="async" loading="lazy" data-image-name="Icon Resource Clay.png" data-image-key="Icon_Resource_Clay.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/c/ca/Icon_Resource_Clay.png/revision/latest/scale-to-width-down/25?cb=20221013133435" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Clay" title="Clay">Clay</a></li>
            <li><a href="/wiki/Copper_Bar" title="Copper Bar"><img alt="Icon Resource CopperBar.png" src="https://static.wikia.nocookie.net/against-the-storm/images/7/73/Icon_Resource_CopperBar.png/revision/latest/scale-to-width-down/25?cb=20221013135448" decoding="async" loading="lazy" data-image-name="Icon Resource CopperBar.png" data-image-key="Icon_Resource_CopperBar.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/7/73/Icon_Resource_CopperBar.png/revision/latest/scale-to-width-down/25?cb=20221013135448" class=" ls-is-cached lazyloaded" width="25" height="25"></a> <a href="/wiki/Copper_Bar" title="Copper Bar">Copper Bar</a></li>
            <li><a href="/wiki/Copper_Ore" title="Copper Ore"><img alt="Icon Resource CopperOre.png" src="https://static.wikia.nocookie.net/against-the-storm/images/a/a9/Icon_Resource_CopperOre.png/revision/latest/scale-to-width-down/25?cb=20221013135616" decoding="async" loading="lazy" data-image-name="Icon Resource CopperOre.png" data-image-key="Icon_Resource_CopperOre.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/a/a9/Icon_Resource_CopperOre.png/revision/latest/scale-to-width-down/25?cb=20221013135616" class=" ls-is-cached lazyloaded" width="25" height="25"></a> <a href="/wiki/Copper_Ore" title="Copper Ore">Copper Ore</a></li>
            <li><a href="/wiki/Crystalized_Dew" title="Crystalized Dew"><img alt="Icon Resource CrystalizedDew.png" src="https://static.wikia.nocookie.net/against-the-storm/images/5/51/Icon_Resource_CrystalizedDew.png/revision/latest/scale-to-width-down/25?cb=20221013135744" decoding="async" loading="lazy" data-image-name="Icon Resource CrystalizedDew.png" data-image-key="Icon_Resource_CrystalizedDew.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/5/51/Icon_Resource_CrystalizedDew.png/revision/latest/scale-to-width-down/25?cb=20221013135744" class=" ls-is-cached lazyloaded" width="25" height="25"></a> <a href="/wiki/Crystalized_Dew" title="Crystalized Dew">Crystalized Dew</a></li>
            <li><a href="/wiki/Flour" title="Flour"><img alt="Icon Resource Flour.png" src="https://static.wikia.nocookie.net/against-the-storm/images/d/d6/Icon_Resource_Flour.png/revision/latest/scale-to-width-down/25?cb=20221012195743" decoding="async" loading="lazy" data-image-name="Icon Resource Flour.png" data-image-key="Icon_Resource_Flour.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/d/d6/Icon_Resource_Flour.png/revision/latest/scale-to-width-down/25?cb=20221012195743" class=" ls-is-cached lazyloaded" width="25" height="25"></a> <a href="/wiki/Flour" title="Flour">Flour</a></li>
            <li><a href="/wiki/Grain" title="Grain"><img alt="Icon Resource Grain.png" src="https://static.wikia.nocookie.net/against-the-storm/images/2/2b/Icon_Resource_Grain.png/revision/latest/scale-to-width-down/25?cb=20221012215701" decoding="async" loading="lazy" data-image-name="Icon Resource Grain.png" data-image-key="Icon_Resource_Grain.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/2/2b/Icon_Resource_Grain.png/revision/latest/scale-to-width-down/25?cb=20221012215701" class=" ls-is-cached lazyloaded" width="25" height="25"></a> <a href="/wiki/Grain" title="Grain">Grain</a></li>
            <li><a href="/wiki/Herbs" title="Herbs"><img alt="Icon Resource Herbs.png" src="https://static.wikia.nocookie.net/against-the-storm/images/0/02/Icon_Resource_Herbs.png/revision/latest/scale-to-width-down/25?cb=20221012215959" decoding="async" loading="lazy" data-image-name="Icon Resource Herbs.png" data-image-key="Icon_Resource_Herbs.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/0/02/Icon_Resource_Herbs.png/revision/latest/scale-to-width-down/25?cb=20221012215959" class=" ls-is-cached lazyloaded" width="25" height="25"></a> <a href="/wiki/Herbs" title="Herbs">Herbs</a></li>
            <li><a href="/wiki/Leather" title="Leather"><img alt="Icon Resource Leather.png" src="https://static.wikia.nocookie.net/against-the-storm/images/a/a9/Icon_Resource_Leather.png/revision/latest/scale-to-width-down/25?cb=20221013133621" decoding="async" loading="lazy" data-image-name="Icon Resource Leather.png" data-image-key="Icon_Resource_Leather.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/a/a9/Icon_Resource_Leather.png/revision/latest/scale-to-width-down/25?cb=20221013133621" class=" ls-is-cached lazyloaded" width="25" height="25"></a> <a href="/wiki/Leather" title="Leather">Leather</a></li>
            <li><a href="/wiki/Pigment" title="Pigment"><img alt="Icon Resource Pigment.png" src="https://static.wikia.nocookie.net/against-the-storm/images/6/61/Icon_Resource_Pigment.png/revision/latest/scale-to-width-down/25?cb=20221012202605" decoding="async" loading="lazy" data-image-name="Icon Resource Pigment.png" data-image-key="Icon_Resource_Pigment.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/6/61/Icon_Resource_Pigment.png/revision/latest/scale-to-width-down/25?cb=20221012202605" class=" ls-is-cached lazyloaded" width="25" height="25"></a> <a href="/wiki/Pigment" title="Pigment">Pigment</a></li>
            <li><a href="/wiki/Plant_Fiber" title="Plant Fiber"><img alt="Icon Resource PlantFiber.png" src="https://static.wikia.nocookie.net/against-the-storm/images/6/6e/Icon_Resource_PlantFiber.png/revision/latest/scale-to-width-down/25?cb=20221025150626" decoding="async" loading="lazy" data-image-name="Icon Resource PlantFiber.png" data-image-key="Icon_Resource_PlantFiber.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/6/6e/Icon_Resource_PlantFiber.png/revision/latest/scale-to-width-down/25?cb=20221025150626" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Plant_Fiber" title="Plant Fiber">Plant Fiber</a></li>
            <li><a href="/wiki/Pottery" title="Pottery"><img alt="Icon Resource Pottery.png" src="https://static.wikia.nocookie.net/against-the-storm/images/b/bc/Icon_Resource_Pottery.png/revision/latest/scale-to-width-down/25?cb=20221013153418" decoding="async" loading="lazy" data-image-name="Icon Resource Pottery.png" data-image-key="Icon_Resource_Pottery.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/b/bc/Icon_Resource_Pottery.png/revision/latest/scale-to-width-down/25?cb=20221013153418" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Pottery" title="Pottery">Pottery</a></li>
            <li><a href="/wiki/Reed" title="Reed"><img alt="Icon Resource Reeds.png" src="https://static.wikia.nocookie.net/against-the-storm/images/7/70/Icon_Resource_Reeds.png/revision/latest/scale-to-width-down/25?cb=20221013134150" decoding="async" loading="lazy" data-image-name="Icon Resource Reeds.png" data-image-key="Icon_Resource_Reeds.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/7/70/Icon_Resource_Reeds.png/revision/latest/scale-to-width-down/25?cb=20221013134150" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Reed" title="Reed">Reed</a></li>
            <li><a href="/wiki/Resin" title="Resin"><img alt="Icon Resource Resin.png" src="https://static.wikia.nocookie.net/against-the-storm/images/6/65/Icon_Resource_Resin.png/revision/latest/scale-to-width-down/25?cb=20221013134420" decoding="async" loading="lazy" data-image-name="Icon Resource Resin.png" data-image-key="Icon_Resource_Resin.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/6/65/Icon_Resource_Resin.png/revision/latest/scale-to-width-down/25?cb=20221013134420" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Resin" title="Resin">Resin</a></li>
            <li><a href="/wiki/Sparkdew" title="Sparkdew"><img alt="Icon Resource Sparkdew.png" src="https://static.wikia.nocookie.net/against-the-storm/images/1/16/Icon_Resource_Sparkdew.png/revision/latest/scale-to-width-down/25?cb=20221013134553" decoding="async" loading="lazy" data-image-name="Icon Resource Sparkdew.png" data-image-key="Icon_Resource_Sparkdew.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/1/16/Icon_Resource_Sparkdew.png/revision/latest/scale-to-width-down/25?cb=20221013134553" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Sparkdew" title="Sparkdew">Sparkdew</a></li>
            <li><a href="/wiki/Stone" title="Stone"><img alt="Icon Resource Stone.png" src="https://static.wikia.nocookie.net/against-the-storm/images/3/3f/Icon_Resource_Stone.png/revision/latest/scale-to-width-down/25?cb=20221013134823" decoding="async" loading="lazy" data-image-name="Icon Resource Stone.png" data-image-key="Icon_Resource_Stone.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/3/3f/Icon_Resource_Stone.png/revision/latest/scale-to-width-down/25?cb=20221013134823" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Stone" title="Stone">Stone</a></li>
            <li><a href="/wiki/Waterskins" title="Waterskins"><img alt="Icon Resource Waterskins.png" src="https://static.wikia.nocookie.net/against-the-storm/images/1/14/Icon_Resource_Waterskins.png/revision/latest/scale-to-width-down/25?cb=20221013153752" decoding="async" loading="lazy" data-image-name="Icon Resource Waterskins.png" data-image-key="Icon_Resource_Waterskins.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/1/14/Icon_Resource_Waterskins.png/revision/latest/scale-to-width-down/25?cb=20221013153752" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Waterskins" title="Waterskins">Waterskins</a></li></ul></li>
    <li><a href="/wiki/Food" title="Food">Food</a>
        <ul><li><a href="/wiki/Berries" title="Berries"><img alt="Icon Resource Berries.png" src="https://static.wikia.nocookie.net/against-the-storm/images/2/25/Icon_Resource_Berries.png/revision/latest/scale-to-width-down/25?cb=20221012214215" decoding="async" loading="lazy" data-image-name="Icon Resource Berries.png" data-image-key="Icon_Resource_Berries.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/2/25/Icon_Resource_Berries.png/revision/latest/scale-to-width-down/25?cb=20221012214215" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Berries" title="Berries">Berries</a></li>
            <li><a href="/wiki/Biscuits" title="Biscuits"><img alt="Icon Resource Biscuits.png" src="https://static.wikia.nocookie.net/against-the-storm/images/c/cd/Icon_Resource_Biscuits.png/revision/latest/scale-to-width-down/25?cb=20221012203344" decoding="async" loading="lazy" data-image-name="Icon Resource Biscuits.png" data-image-key="Icon_Resource_Biscuits.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/c/cd/Icon_Resource_Biscuits.png/revision/latest/scale-to-width-down/25?cb=20221012203344" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Biscuits" title="Biscuits">Biscuits</a></li>
            <li><a href="/wiki/Eggs" title="Eggs"><img alt="Icon Resource Eggs.png" src="https://static.wikia.nocookie.net/against-the-storm/images/6/67/Icon_Resource_Eggs.png/revision/latest/scale-to-width-down/25?cb=20221012215251" decoding="async" loading="lazy" data-image-name="Icon Resource Eggs.png" data-image-key="Icon_Resource_Eggs.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/6/67/Icon_Resource_Eggs.png/revision/latest/scale-to-width-down/25?cb=20221012215251" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Eggs" title="Eggs">Eggs</a></li>
            <li><a href="/wiki/Insects" title="Insects"><img alt="Icon Resource Insects.png" src="https://static.wikia.nocookie.net/against-the-storm/images/7/7c/Icon_Resource_Insects.png/revision/latest/scale-to-width-down/25?cb=20221013125016" decoding="async" loading="lazy" data-image-name="Icon Resource Insects.png" data-image-key="Icon_Resource_Insects.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/7/7c/Icon_Resource_Insects.png/revision/latest/scale-to-width-down/25?cb=20221013125016" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Insects" title="Insects">Insects</a></li>
            <li><a href="/wiki/Jerky" title="Jerky"><img alt="Icon Resource Jerky.png" src="https://static.wikia.nocookie.net/against-the-storm/images/6/6f/Icon_Resource_Jerky.png/revision/latest/scale-to-width-down/25?cb=20221012204322" decoding="async" loading="lazy" data-image-name="Icon Resource Jerky.png" data-image-key="Icon_Resource_Jerky.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/6/6f/Icon_Resource_Jerky.png/revision/latest/scale-to-width-down/25?cb=20221012204322" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Jerky" title="Jerky">Jerky</a></li>
            <li><a href="/wiki/Meat" title="Meat"><img alt="Icon Resource Meat.png" src="https://static.wikia.nocookie.net/against-the-storm/images/e/e1/Icon_Resource_Meat.png/revision/latest/scale-to-width-down/25?cb=20221013125305" decoding="async" loading="lazy" data-image-name="Icon Resource Meat.png" data-image-key="Icon_Resource_Meat.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/e/e1/Icon_Resource_Meat.png/revision/latest/scale-to-width-down/25?cb=20221013125305" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Meat" title="Meat">Meat</a></li>
            <li><a href="/wiki/Mushrooms" title="Mushrooms"><img alt="Icon Resource Mushrooms.png" src="https://static.wikia.nocookie.net/against-the-storm/images/f/f8/Icon_Resource_Mushrooms.png/revision/latest/scale-to-width-down/25?cb=20221013125816" decoding="async" loading="lazy" data-image-name="Icon Resource Mushrooms.png" data-image-key="Icon_Resource_Mushrooms.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/f/f8/Icon_Resource_Mushrooms.png/revision/latest/scale-to-width-down/25?cb=20221013125816" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Mushrooms" title="Mushrooms">Mushrooms</a></li>
            <li><a href="/wiki/Pickled_Goods" title="Pickled Goods"><img alt="Icon Resource PickledGoods.png" src="https://static.wikia.nocookie.net/against-the-storm/images/e/e3/Icon_Resource_PickledGoods.png/revision/latest/scale-to-width-down/25?cb=20221012204558" decoding="async" loading="lazy" data-image-name="Icon Resource PickledGoods.png" data-image-key="Icon_Resource_PickledGoods.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/e/e3/Icon_Resource_PickledGoods.png/revision/latest/scale-to-width-down/25?cb=20221012204558" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Pickled_Goods" title="Pickled Goods">Pickled Goods</a></li>
            <li><a href="/wiki/Pie" title="Pie"><img alt="Icon Resource Pie.png" src="https://static.wikia.nocookie.net/against-the-storm/images/3/36/Icon_Resource_Pie.png/revision/latest/scale-to-width-down/25?cb=20221012204820" decoding="async" loading="lazy" data-image-name="Icon Resource Pie.png" data-image-key="Icon_Resource_Pie.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/3/36/Icon_Resource_Pie.png/revision/latest/scale-to-width-down/25?cb=20221012204820" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Pie" title="Pie">Pie</a></li>
            <li><a href="/wiki/Roots" title="Roots"><img alt="Icon Resource Roots.png" src="https://static.wikia.nocookie.net/against-the-storm/images/b/b6/Icon_Resource_Roots.png/revision/latest/scale-to-width-down/25?cb=20221013130208" decoding="async" loading="lazy" data-image-name="Icon Resource Roots.png" data-image-key="Icon_Resource_Roots.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/b/b6/Icon_Resource_Roots.png/revision/latest/scale-to-width-down/25?cb=20221013130208" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Roots" title="Roots">Roots</a></li>
            <li><a href="/wiki/Skewers" title="Skewers"><img alt="Icon Resource Skewers.png" src="https://static.wikia.nocookie.net/against-the-storm/images/1/10/Icon_Resource_Skewers.png/revision/latest/scale-to-width-down/25?cb=20221012205320" decoding="async" loading="lazy" data-image-name="Icon Resource Skewers.png" data-image-key="Icon_Resource_Skewers.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/1/10/Icon_Resource_Skewers.png/revision/latest/scale-to-width-down/25?cb=20221012205320" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Skewers" title="Skewers">Skewers</a></li>
            <li><a href="/wiki/Vegetables" title="Vegetables"><img alt="Icon Resource Vegetables.png" src="https://static.wikia.nocookie.net/against-the-storm/images/e/ea/Icon_Resource_Vegetables.png/revision/latest/scale-to-width-down/25?cb=20221013130356" decoding="async" loading="lazy" data-image-name="Icon Resource Vegetables.png" data-image-key="Icon_Resource_Vegetables.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/e/ea/Icon_Resource_Vegetables.png/revision/latest/scale-to-width-down/25?cb=20221013130356" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Vegetables" title="Vegetables">Vegetables</a></li></ul></li>
    <li><span class="new" title="Fuel &amp; Exploration (page does not exist)" data-uncrawlable-url="L3dpa2kvRnVlbF8lMjZfRXhwbG9yYXRpb24/YWN0aW9uPWVkaXQmcmVkbGluaz0x">Fuel &amp; Exploration</span>
        <ul><li><a href="/wiki/Coal" title="Coal"><img alt="Icon Resource Coal.png" src="https://static.wikia.nocookie.net/against-the-storm/images/e/e9/Icon_Resource_Coal.png/revision/latest/scale-to-width-down/25?cb=20221012202416" decoding="async" loading="lazy" data-image-name="Icon Resource Coal.png" data-image-key="Icon_Resource_Coal.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/e/e9/Icon_Resource_Coal.png/revision/latest/scale-to-width-down/25?cb=20221012202416" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Coal" title="Coal">Coal</a></li>
            <li><a href="/wiki/Infused_Tools" title="Infused Tools"><img alt="Icon Resource InfusedTools.png" src="https://static.wikia.nocookie.net/against-the-storm/images/3/38/Icon_Resource_InfusedTools.png/revision/latest/scale-to-width-down/25?cb=20221013152023" decoding="async" loading="lazy" data-image-name="Icon Resource InfusedTools.png" data-image-key="Icon_Resource_InfusedTools.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/3/38/Icon_Resource_InfusedTools.png/revision/latest/scale-to-width-down/25?cb=20221013152023" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Infused_Tools" title="Infused Tools">Infused Tools</a></li>
            <li><a href="/wiki/Oil" title="Oil"><img alt="Icon Resource Oil.png" src="https://static.wikia.nocookie.net/against-the-storm/images/0/0d/Icon_Resource_Oil.png/revision/latest/scale-to-width-down/25?cb=20221012201635" decoding="async" loading="lazy" data-image-name="Icon Resource Oil.png" data-image-key="Icon_Resource_Oil.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/0/0d/Icon_Resource_Oil.png/revision/latest/scale-to-width-down/25?cb=20221012201635" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Oil" title="Oil">Oil</a></li>
            <li><a href="/wiki/Purging_Fire" title="Purging Fire"><img alt="Icon Resource PurgingFire.png" src="https://static.wikia.nocookie.net/against-the-storm/images/9/96/Icon_Resource_PurgingFire.png/revision/latest/scale-to-width-down/25?cb=20221013153952" decoding="async" loading="lazy" data-image-name="Icon Resource PurgingFire.png" data-image-key="Icon_Resource_PurgingFire.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/9/96/Icon_Resource_PurgingFire.png/revision/latest/scale-to-width-down/25?cb=20221013153952" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Purging_Fire" title="Purging Fire">Purging Fire</a></li>
            <li><a href="/wiki/Sea_Marrow" title="Sea Marrow"><img alt="Icon Resource SeaMarrow.png" src="https://static.wikia.nocookie.net/against-the-storm/images/8/86/Icon_Resource_SeaMarrow.png/revision/latest/scale-to-width-down/25?cb=20221012202959" decoding="async" loading="lazy" data-image-name="Icon Resource SeaMarrow.png" data-image-key="Icon_Resource_SeaMarrow.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/8/86/Icon_Resource_SeaMarrow.png/revision/latest/scale-to-width-down/25?cb=20221012202959" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Sea_Marrow" title="Sea Marrow">Sea Marrow</a></li>
            <li><a href="/wiki/Simple_Tools" title="Simple Tools"><img alt="Icon Resource SimpleTools.png" src="https://static.wikia.nocookie.net/against-the-storm/images/5/54/Icon_Resource_SimpleTools.png/revision/latest/scale-to-width-down/25?cb=20221013152255" decoding="async" loading="lazy" data-image-name="Icon Resource SimpleTools.png" data-image-key="Icon_Resource_SimpleTools.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/5/54/Icon_Resource_SimpleTools.png/revision/latest/scale-to-width-down/25?cb=20221013152255" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Simple_Tools" title="Simple Tools">Simple Tools</a></li>
            <li><a href="/wiki/Wood" title="Wood"><img alt="Icon Resource Wood.png" src="https://static.wikia.nocookie.net/against-the-storm/images/8/84/Icon_Resource_Wood.png/revision/latest/scale-to-width-down/25?cb=20221013135246" decoding="async" loading="lazy" data-image-name="Icon Resource Wood.png" data-image-key="Icon_Resource_Wood.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/8/84/Icon_Resource_Wood.png/revision/latest/scale-to-width-down/25?cb=20221013135246" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Wood" title="Wood">Wood</a></li></ul></li>
    <li><span class="new" title="Trade Goods (page does not exist)" data-uncrawlable-url="L3dpa2kvVHJhZGVfR29vZHM/YWN0aW9uPWVkaXQmcmVkbGluaz0x">Trade Goods</span>
        <ul><li><a href="/wiki/Amber" title="Amber"><img alt="Icon Resource Amber.png" src="https://static.wikia.nocookie.net/against-the-storm/images/2/22/Icon_Resource_Amber.png/revision/latest/scale-to-width-down/25?cb=20221013152437" decoding="async" loading="lazy" data-image-name="Icon Resource Amber.png" data-image-key="Icon_Resource_Amber.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/2/22/Icon_Resource_Amber.png/revision/latest/scale-to-width-down/25?cb=20221013152437" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Amber" title="Amber">Amber</a></li>
            <li><a href="/wiki/Ancient_Tablet" title="Ancient Tablet"><img alt="Icon Resource AncientTablet.png" src="https://static.wikia.nocookie.net/against-the-storm/images/1/1c/Icon_Resource_AncientTablet.png/revision/latest/scale-to-width-down/25?cb=20221013152622" decoding="async" loading="lazy" data-image-name="Icon Resource AncientTablet.png" data-image-key="Icon_Resource_AncientTablet.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/1/1c/Icon_Resource_AncientTablet.png/revision/latest/scale-to-width-down/25?cb=20221013152622" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Ancient_Tablet" title="Ancient Tablet">Ancient Tablet</a></li>
            <li><a href="/wiki/Artifacts" title="Artifacts"><img alt="Icon MetaResource Artifact.png" src="https://static.wikia.nocookie.net/against-the-storm/images/f/f1/Icon_MetaResource_Artifact.png/revision/latest/scale-to-width-down/25?cb=20221101090204" decoding="async" loading="lazy" data-image-name="Icon MetaResource Artifact.png" data-image-key="Icon_MetaResource_Artifact.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/f/f1/Icon_MetaResource_Artifact.png/revision/latest/scale-to-width-down/25?cb=20221101090204" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Artifacts" title="Artifacts">Artifacts</a></li>
            <li><a href="/wiki/Food_Stockpiles" title="Food Stockpiles"><img alt="Icon MetaResource FoodStockpiles.png" src="https://static.wikia.nocookie.net/against-the-storm/images/7/78/Icon_MetaResource_FoodStockpiles.png/revision/latest/scale-to-width-down/25?cb=20221013154910" decoding="async" loading="lazy" data-image-name="Icon MetaResource FoodStockpiles.png" data-image-key="Icon_MetaResource_FoodStockpiles.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/7/78/Icon_MetaResource_FoodStockpiles.png/revision/latest/scale-to-width-down/25?cb=20221013154910" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Food_Stockpiles" title="Food Stockpiles">Food Stockpiles</a></li>
            <li><a href="/wiki/Machinery" title="Machinery"><img alt="Icon MetaResource Machinery.png" src="https://static.wikia.nocookie.net/against-the-storm/images/2/23/Icon_MetaResource_Machinery.png/revision/latest/scale-to-width-down/25?cb=20221013155040" decoding="async" loading="lazy" data-image-name="Icon MetaResource Machinery.png" data-image-key="Icon_MetaResource_Machinery.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/2/23/Icon_MetaResource_Machinery.png/revision/latest/scale-to-width-down/25?cb=20221013155040" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Machinery" title="Machinery">Machinery</a></li>
            <li><a href="/wiki/Pack_of_Building_Materials" title="Pack of Building Materials"><img alt="Icon Resource BuildingMaterials.png" src="https://static.wikia.nocookie.net/against-the-storm/images/2/26/Icon_Resource_BuildingMaterials.png/revision/latest/scale-to-width-down/25?cb=20221013151015" decoding="async" loading="lazy" data-image-name="Icon Resource BuildingMaterials.png" data-image-key="Icon_Resource_BuildingMaterials.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/2/26/Icon_Resource_BuildingMaterials.png/revision/latest/scale-to-width-down/25?cb=20221013151015" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Pack_of_Building_Materials" title="Pack of Building Materials">Pack of Building Materials</a></li>
            <li><a href="/wiki/Pack_of_Crops" title="Pack of Crops"><img alt="Icon Resource Crops.png" src="https://static.wikia.nocookie.net/against-the-storm/images/9/95/Icon_Resource_Crops.png/revision/latest/scale-to-width-down/25?cb=20221013151255" decoding="async" loading="lazy" data-image-name="Icon Resource Crops.png" data-image-key="Icon_Resource_Crops.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/9/95/Icon_Resource_Crops.png/revision/latest/scale-to-width-down/25?cb=20221013151255" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Pack_of_Crops" title="Pack of Crops">Pack of Crops</a></li>
            <li><a href="/wiki/Pack_of_Luxury_Goods" title="Pack of Luxury Goods"><img alt="Icon Resource Luxury.png" src="https://static.wikia.nocookie.net/against-the-storm/images/f/fe/Icon_Resource_Luxury.png/revision/latest/scale-to-width-down/25?cb=20221013151444" decoding="async" loading="lazy" data-image-name="Icon Resource Luxury.png" data-image-key="Icon_Resource_Luxury.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/f/fe/Icon_Resource_Luxury.png/revision/latest/scale-to-width-down/25?cb=20221013151444" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Pack_of_Luxury_Goods" title="Pack of Luxury Goods">Pack of Luxury Goods</a></li>
            <li><a href="/wiki/Pack_of_Provisions" title="Pack of Provisions"><img alt="Icon Resource Provisions.png" src="https://static.wikia.nocookie.net/against-the-storm/images/c/cb/Icon_Resource_Provisions.png/revision/latest/scale-to-width-down/25?cb=20221013151648" decoding="async" loading="lazy" data-image-name="Icon Resource Provisions.png" data-image-key="Icon_Resource_Provisions.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/c/cb/Icon_Resource_Provisions.png/revision/latest/scale-to-width-down/25?cb=20221013151648" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Pack_of_Provisions" title="Pack of Provisions">Pack of Provisions</a></li>
            <li><a href="/wiki/Pack_of_Trade_Goods" title="Pack of Trade Goods"><img alt="Icon Resource TradeGoods.png" src="https://static.wikia.nocookie.net/against-the-storm/images/a/a5/Icon_Resource_TradeGoods.png/revision/latest/scale-to-width-down/25?cb=20221013151828" decoding="async" loading="lazy" data-image-name="Icon Resource TradeGoods.png" data-image-key="Icon_Resource_TradeGoods.png" data-src="https://static.wikia.nocookie.net/against-the-storm/images/a/a5/Icon_Resource_TradeGoods.png/revision/latest/scale-to-width-down/25?cb=20221013151828" class=" lazyloaded" width="25" height="25"></a> <a href="/wiki/Pack_of_Trade_Goods" title="Pack of Trade Goods">Pack of Trade Goods</a></li></ul></li></ul>
